import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./provider";
import { store } from "./redux/store";
import "./globals.css";
import Nav from "./(components)/nav/nav";
import WeekTop from "./(components)/sections/weekTop10";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          {/* <Nav /> */}
          <Providers>
            {children}
          </Providers>
          {/* <WeekTop /> */}
        </div>
      </body>
    </html>
  );
}
