import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./nav/nav";
import WeekTop from "./sections/weekTop10";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-wrap w-screen">
            <Nav />
                {children}
          <WeekTop />
        </div>
      </body>
    </html>
  );
}
